import React,{useEffect,useMemo,useRef,useState} from 'react';
import { Camera, MapPin, Navigation, CheckCircle2, Play, WifiOff, AlertTriangle, PackageCheck, LocateFixed } from 'lucide-react';
import { request, assetUrl } from '../api';

export default function Driver(){
 const [stops,setStops]=useState([]),[error,setError]=useState(''),[online,setOnline]=useState(navigator.onLine),[tracking,setTracking]=useState(false),[position,setPosition]=useState(null),[busy,setBusy]=useState(null);
 const watchRef=useRef(null);
 const load=()=>request('/stops').then(setStops).catch(e=>setError(e.message));
 useEffect(()=>{load();const timer=setInterval(load,15000);const on=()=>setOnline(navigator.onLine);addEventListener('online',on);addEventListener('offline',on);return()=>{clearInterval(timer);removeEventListener('online',on);removeEventListener('offline',on);if(watchRef.current)navigator.geolocation.clearWatch(watchRef.current)}},[]);
 const completed=stops.filter(s=>s.status==='DELIVERED').length;
 const next=stops.find(s=>s.status!=='DELIVERED');
 const remainingBoxes=stops.filter(s=>s.status!=='DELIVERED').reduce((n,s)=>n+s.boxCount,0);
 async function status(id,value){setBusy(id);try{await request(`/stops/${id}`,{method:'PATCH',body:JSON.stringify({status:value})});await load()}catch(e){queueAction({type:'status',id,value});setError('Saved offline. It will sync when connection returns.')}finally{setBusy(null)}}
 async function photo(id,file){if(!file)return;setBusy(id);try{const fd=new FormData();fd.append('photo',file);await request(`/stops/${id}/photo`,{method:'POST',body:fd});await load()}catch(e){setError('Photo upload requires an internet connection.')}finally{setBusy(null)}}
 function startTracking(){if(!navigator.geolocation)return setError('Location is not supported on this device.');setTracking(true);watchRef.current=navigator.geolocation.watchPosition(async p=>{const data={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,speed:p.coords.speed,heading:p.coords.heading};setPosition(data);try{await request('/driver/location',{method:'POST',body:JSON.stringify(data)})}catch{}},e=>setError(e.message),{enableHighAccuracy:true,maximumAge:10000,timeout:15000})}
 function stopTracking(){if(watchRef.current)navigator.geolocation.clearWatch(watchRef.current);watchRef.current=null;setTracking(false)}
 useEffect(()=>{if(online)syncQueue(load)},[online]);
 return <main className="page driver-page phase3-driver">
  <section className="hero driver-hero"><div><div className="eyebrow">PHASE 3 · DRIVER PWA</div><h1>Your delivery route</h1><p>{completed} of {stops.length} completed · {remainingBoxes} boxes remaining</p></div><div className="driver-live"><span className={online?'online':'offline'}>{online?'Online':'Offline'}</span><button onClick={tracking?stopTracking:startTracking}>{tracking?<><LocateFixed size={17}/> Stop tracking</>:<><Play size={17}/> Start route</>}</button></div></section>
  {!online&&<div className="notice offline-notice"><WifiOff size={18}/> Offline mode is active. Status changes are queued.</div>}{error&&<div className="error">{error}</div>}
  {next&&<section className="next-stop-card"><div><span>NEXT STOP</span><h2>{next.customer.name}</h2><p>{next.customer.address}</p></div><a className="button" target="_blank" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(next.customer.address)}`}><Navigation size={17}/> Navigate</a></section>}
  <section className="driver-summary"><div><b>{completed}/{stops.length}</b><span>Stops</span></div><div><b>{remainingBoxes}</b><span>Boxes left</span></div><div><b>{position?`${Math.round(position.accuracy)}m`:'—'}</b><span>GPS accuracy</span></div></section>
  <div className="driver-list">{stops.length===0?<div className="panel empty">No stops have been assigned yet.</div>:stops.map((s,i)=><article className={`driver-stop ${s.status==='DELIVERED'?'done':''}`} key={s.id}><div className="stop-index">{i+1}</div><div className="stop-body"><span className="badge">{s.status.replace('_',' ')}</span><h2>{s.customer.name}</h2><p><MapPin size={15}/>{s.customer.address}</p><div className="stop-meta"><b>{s.boxCount} boxes</b><span>Invoice {s.invoiceNumber||'—'}</span><span>{s.estimatedServiceMinutes} min service</span></div>{s.notes&&<div className="driver-note"><AlertTriangle size={16}/>{s.notes}</div>}{s.proofPhotoUrl&&<img className="proof" src={assetUrl(s.proofPhotoUrl)} alt="Proof of delivery"/>}<div className="actions"><a className="button secondary" target="_blank" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(s.customer.address)}`}><Navigation size={16}/> Navigate</a>{s.status!=='DELIVERED'&&<button disabled={busy===s.id} onClick={()=>status(s.id,s.status==='ARRIVED'?'EN_ROUTE':'ARRIVED')}>{s.status==='ARRIVED'?'Resume':'Arrived'}</button>}<label className="button secondary"><Camera size={16}/> Photo<input hidden type="file" accept="image/*" capture="environment" onChange={e=>photo(s.id,e.target.files[0])}/></label>{s.status!=='DELIVERED'&&<button className="issue-button" disabled={busy===s.id} onClick={()=>{const note=prompt('Describe the delivery issue or shortage:');if(note)request(`/stops/${s.id}`,{method:'PATCH',body:JSON.stringify({status:'ISSUE',notes:note})}).then(load)}}><AlertTriangle size={16}/> Report issue</button>}{s.status!=='DELIVERED'&&<button className="success" disabled={busy===s.id||!s.proofPhotoUrl} title={!s.proofPhotoUrl?'Upload a delivery photo first':''} onClick={()=>status(s.id,'DELIVERED')}><PackageCheck size={16}/> Delivered</button>}</div></div></article>)}</div>
 </main>
}
function queueAction(action){const q=JSON.parse(localStorage.getItem('driverQueue')||'[]');q.push(action);localStorage.setItem('driverQueue',JSON.stringify(q))}
async function syncQueue(done){const q=JSON.parse(localStorage.getItem('driverQueue')||'[]');if(!q.length)return;const left=[];for(const a of q){try{if(a.type==='status')await request(`/stops/${a.id}`,{method:'PATCH',body:JSON.stringify({status:a.value})})}catch{left.push(a)}}localStorage.setItem('driverQueue',JSON.stringify(left));done()}
