import React,{useEffect,useMemo,useState} from 'react';
import { Upload, Users, MapPinned, FileCheck2, RefreshCw, Sparkles, Navigation, Clock3, Package, DollarSign, GripVertical, Map, BarChart3 } from 'lucide-react';
import { request } from '../api';
import Reports from './Reports';

const depot={lat:41.7658,lng:-72.6734};
const fmtTime=m=>`${Math.floor(m/60)}h ${m%60}m`;
const tone=(m,target)=>m>target+30?'over':m<target-60?'under':'balanced';

export default function Manager(){
 const [live,setLive]=useState([]),[drivers,setDrivers]=useState([]),[stops,setStops]=useState([]),[invoices,setInvoices]=useState([]),[dispatch,setDispatch]=useState({drivers:[],unassigned:[]}),[file,setFile]=useState(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[tab,setTab]=useState('dispatch'),[selected,setSelected]=useState(null),[dragged,setDragged]=useState(null);
 const load=async()=>{const [d,s,i,x]=await Promise.all([request('/drivers'),request('/stops'),request('/invoices'),request('/dispatch')]);setDrivers(d);setStops(s);setInvoices(i);setDispatch(x)};
 useEffect(()=>{load();const poll=()=>request('/driver/live').then(setLive).catch(()=>{});poll();const t=setInterval(poll,15000);return()=>clearInterval(t)},[]);
 const pending=useMemo(()=>invoices.flatMap(i=>i.extracted.filter(x=>x.reviewStatus==='PENDING').map(x=>({...x,upload:i}))),[invoices]);
 const allMapStops=useMemo(()=>[...dispatch.unassigned,...dispatch.drivers.flatMap(d=>d.stops.map(s=>({...s,color:d.color,driverName:d.user.name})))],[dispatch]);
 async function upload(e){e.preventDefault();if(!file)return;setBusy(true);setMsg('');try{const fd=new FormData();fd.append('invoice',file);await request('/invoices/upload',{method:'POST',body:fd});setMsg('Invoice extracted. Review the rows below.');setFile(null);await load();setTab('review')}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 async function edit(id,key,value){await request(`/extracted/${id}`,{method:'PATCH',body:JSON.stringify({[key]:value})});await load()}
 async function approve(id){await request(`/extracted/${id}/approve`,{method:'POST'});await load()}
 async function assign(stopId,driverId){await request(`/stops/${stopId}`,{method:'PATCH',body:JSON.stringify({driverId:driverId||null,status:driverId?'ASSIGNED':'UNASSIGNED'})});await load()}
 async function balance(){setBusy(true);await request('/dispatch/balance',{method:'POST'});await load();setBusy(false);setMsg('Routes balanced toward each driver’s 5–6 hour target.')}
 async function optimize(driverId){await request(`/dispatch/optimize/${driverId}`,{method:'POST'});await load()}
 async function updateDriver(id,key,value){await request(`/drivers/${id}`,{method:'PATCH',body:JSON.stringify({[key]:value})});await load()}
 function drop(driverId){if(dragged)assign(dragged,driverId);setDragged(null)}
 return <main className="page wide"><section className="hero compact"><div><div className="eyebrow">PHASE 4 · COMPLETE OPERATIONS</div><h1>Build balanced routes on the map</h1><p>Move stops between drivers and watch time, boxes and invoice value recalculate.</p></div><div className="hero-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/> Refresh</button><button onClick={balance} disabled={busy}><Sparkles size={16}/>{busy?'Balancing…':'Balance all routes'}</button></div></section>
 <section className="stats"><Stat icon={<MapPinned/>} label="Delivery stops" value={stops.length}/><Stat icon={<Users/>} label="Active drivers" value={drivers.filter(d=>d.active).length}/><Stat icon={<FileCheck2/>} label="Awaiting review" value={pending.length}/></section>
 <nav className="tabs"><button className={tab==='dispatch'?'active':''} onClick={()=>setTab('dispatch')}><Map size={16}/> Dispatch board</button><button className={tab==='upload'?'active':''} onClick={()=>setTab('upload')}><Upload size={16}/> Upload invoices</button><button className={tab==='review'?'active':''} onClick={()=>setTab('review')}><FileCheck2 size={16}/> Review ({pending.length})</button><button className={tab==='reports'?'active':''} onClick={()=>setTab('reports')}><BarChart3 size={16}/> Reports</button></nav>
 {msg&&<div className="notice">{msg}</div>}{tab==='dispatch'&&<LiveDrivers drivers={live}/>}
 {tab==='dispatch'&&<DispatchBoard dispatch={dispatch} allStops={allMapStops} selected={selected} setSelected={setSelected} dragged={dragged} setDragged={setDragged} drop={drop} assign={assign} optimize={optimize} updateDriver={updateDriver}/>} 
 {tab==='upload'&&<section className="panel"><div className="panel-title"><div><h2>Daily invoice upload</h2><p>Upload a PDF, JPG or PNG. Approved customers become unassigned map pins.</p></div><Upload/></div><form className="upload" onSubmit={upload}><input type="file" accept="application/pdf,image/*" onChange={e=>setFile(e.target.files[0])}/><button disabled={busy||!file}>{busy?'Extracting…':'Upload and extract'}</button></form></section>}
 {tab==='reports'&&<Reports/>}
 {tab==='review'&&<section className="panel"><h2>Extraction review</h2><p>Correct uncertain fields before creating delivery stops.</p>{pending.length===0?<div className="empty">No rows waiting for review.</div>:<div className="table-wrap"><table><thead><tr><th>Customer</th><th>Address</th><th>Invoice</th><th>Value</th><th>Boxes</th><th>Confidence</th><th></th></tr></thead><tbody>{pending.map(x=><tr key={x.id}><td><input value={x.customerName} onChange={e=>edit(x.id,'customerName',e.target.value)}/></td><td><input value={x.address} onChange={e=>edit(x.id,'address',e.target.value)}/></td><td><input value={x.invoiceNumber||''} onChange={e=>edit(x.id,'invoiceNumber',e.target.value)}/></td><td><input type="number" value={x.invoiceValue} onChange={e=>edit(x.id,'invoiceValue',e.target.value)}/></td><td><input type="number" value={x.boxCount} onChange={e=>edit(x.id,'boxCount',e.target.value)}/></td><td><span className={x.confidence<.7?'badge warn':'badge'}>{Math.round(x.confidence*100)}%</span></td><td><button onClick={()=>approve(x.id)}>Approve</button></td></tr>)}</tbody></table></div>}</section>}
 </main>
}

function DispatchBoard({dispatch,allStops,selected,setSelected,dragged,setDragged,drop,assign,optimize,updateDriver}){
 return <section className="dispatch-layout">
  <aside className="unassigned column-panel" onDragOver={e=>e.preventDefault()} onDrop={()=>drop(null)}><div className="column-head"><div><span className="kicker">QUEUE</span><h2>Unassigned stops</h2></div><span className="count">{dispatch.unassigned.length}</span></div><p>Drag a card onto a driver route.</p><div className="stop-stack">{dispatch.unassigned.map(s=><StopCard key={s.id} stop={s} selected={selected} setSelected={setSelected} setDragged={setDragged}/>)}</div></aside>
  <div className="map-panel"><MapCanvas stops={allStops} selected={selected} setSelected={setSelected}/><div className="map-legend"><span><i className="pin unassigned-pin"/>Unassigned</span>{dispatch.drivers.map(d=><span key={d.id}><i className="pin" style={{background:d.color}}/>{d.user.name}</span>)}</div></div>
  <aside className="driver-routes">{dispatch.drivers.map(d=><DriverLane key={d.id} driver={d} selected={selected} setSelected={setSelected} setDragged={setDragged} drop={drop} assign={assign} optimize={optimize} updateDriver={updateDriver}/>)}</aside>
 </section>
}

function MapCanvas({stops,selected,setSelected}){
 const project=(lat,lng)=>({left:`${8+(lng+73.05)/.72*84}%`,top:`${92-(lat-41.55)/.48*84}%`});
 return <div className="route-map"><div className="map-grid"/><div className="depot" style={project(depot.lat,depot.lng)}>W</div>{stops.map((s,i)=>{const p=project(s.customer.latitude||depot.lat,s.customer.longitude||depot.lng);return <button title={`${s.customer.name} — ${s.boxCount} boxes`} key={s.id} className={`map-marker ${selected===s.id?'selected':''}`} style={{...p,background:s.color||'#64748b'}} onClick={()=>setSelected(s.id)}>{i+1}</button>})}<div className="map-note">Visual planning map · road routing provider can be connected in production</div></div>
}

function DriverLane({driver,selected,setSelected,setDragged,drop,assign,optimize,updateDriver}){
 const m=driver.metrics,t=tone(m.totalMinutes,driver.targetMinutes);
 return <article className={`driver-lane ${t}`} style={{'--driver':driver.color}} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(driver.id)}><div className="driver-head"><div className="driver-avatar" style={{background:driver.color}}>{driver.user.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><h3>{driver.user.name}</h3><span>{m.stops} stops · {m.distanceMiles} mi</span></div><label className="active-toggle"><input type="checkbox" checked={driver.active} onChange={e=>updateDriver(driver.id,'active',e.target.checked)}/> Active</label></div><div className="workload"><div className="workload-row"><strong>{fmtTime(m.totalMinutes)}</strong><span>Target {fmtTime(driver.targetMinutes)}</span></div><div className="meter"><i style={{width:`${Math.min(100,m.totalMinutes/driver.targetMinutes*100)}%`}}/></div><div className="route-metrics"><span><Clock3/> {fmtTime(m.drivingMinutes)} drive</span><span><Package/> {m.boxes}/{driver.maxBoxes}</span><span><DollarSign/> ${Math.round(m.invoiceValue).toLocaleString()}</span></div></div><div className="driver-controls"><label>Target <select value={driver.targetMinutes} onChange={e=>updateDriver(driver.id,'targetMinutes',e.target.value)}><option value="300">5 hours</option><option value="330">5.5 hours</option><option value="360">6 hours</option></select></label><button className="mini" onClick={()=>optimize(driver.id)}><Navigation size={14}/>Optimize order</button></div><div className="lane-stops">{driver.stops.map((s,i)=><StopCard key={s.id} stop={s} index={i+1} selected={selected} setSelected={setSelected} setDragged={setDragged} onUnassign={()=>assign(s.id,null)}/>) }{driver.stops.length===0&&<div className="drop-zone">Drop stops here</div>}</div></article>
}

function StopCard({stop,index,selected,setSelected,setDragged,onUnassign}){return <article draggable onDragStart={()=>setDragged(stop.id)} onClick={()=>setSelected(stop.id)} className={`dispatch-stop ${selected===stop.id?'selected':''}`}><GripVertical size={17}/><span className="sequence">{index||'•'}</span><div className="stop-copy"><strong>{stop.customer.name}</strong><small>{stop.customer.address}</small><div><span>{stop.boxCount} boxes</span><span>${Math.round(stop.invoiceValue).toLocaleString()}</span><span>{stop.estimatedServiceMinutes} min</span></div></div>{onUnassign&&<button className="x" onClick={e=>{e.stopPropagation();onUnassign()}}>×</button>}</article>}
function Stat({icon,label,value}){return <div className="stat"><div>{icon}</div><span>{label}</span><b>{value}</b></div>}

function LiveDrivers({drivers}){return <section className="live-strip"><div className="live-title"><span className="live-dot"/>LIVE DRIVER TRACKING</div><div className="live-grid">{drivers.map(d=><article key={d.id}><i style={{background:d.color}}/ ><div><strong>{d.name}</strong><span>{d.currentStop?`Stop: ${d.currentStop.customer.name}`:'Waiting for route'}</span></div><div className="live-status"><b>{d.remainingStops}</b><span>left</span><small>{d.locationUpdatedAt?new Date(d.locationUpdatedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'No GPS yet'}</small></div></article>)}</div></section>}
