import React,{useEffect,useMemo,useState} from 'react';
import { AlertTriangle, BarChart3, Boxes, CheckCircle2, Download, DollarSign, RefreshCw, Route, ShieldAlert } from 'lucide-react';
import { request, API } from '../api';

const today=()=>new Date().toISOString().slice(0,10);
const money=n=>`$${Math.round(n||0).toLocaleString()}`;
export default function Reports(){
 const [date,setDate]=useState(today()),[report,setReport]=useState(null),[history,setHistory]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setBusy(true);setError('');try{const [r,h]=await Promise.all([request(`/reports/daily?date=${date}`),request('/reports/history?days=30')]);setReport(r);setHistory(h)}catch(e){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[date]);
 async function download(){const token=localStorage.getItem('token');const response=await fetch(`${API}/reports/export.csv?date=${date}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)return setError('Could not export report');const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`bread-route-${date}.csv`;a.click();URL.revokeObjectURL(url)}
 const max=useMemo(()=>Math.max(1,...history.map(x=>x.stops)),[history]);
 if(!report)return <section className="panel">{error||'Loading reports…'}</section>;
 const s=report.summary;
 return <div className="reports-page">
  <section className="report-toolbar"><div><span className="kicker">PHASE 4 · OPERATIONS INTELLIGENCE</span><h2>Daily delivery report</h2><p>Performance, shortages, proof status and driver results in one place.</p></div><div><input type="date" value={date} onChange={e=>setDate(e.target.value)}/><button className="secondary" onClick={load} disabled={busy}><RefreshCw size={16}/>Refresh</button><button onClick={download}><Download size={16}/>Export CSV</button></div></section>
  {error&&<div className="error">{error}</div>}
  <section className="report-kpis"><Kpi icon={<Route/>} label="Completed stops" value={`${s.completedStops}/${s.totalStops}`} note={`${s.completionRate}% complete`}/><Kpi icon={<Boxes/>} label="Boxes delivered" value={`${s.deliveredBoxes}/${s.totalBoxes}`} note="Delivered / expected"/><Kpi icon={<DollarSign/>} label="Invoice value" value={money(s.invoiceValue)} note="Assigned for the day"/><Kpi icon={<ShieldAlert/>} label="Issues" value={s.issueStops} note={`${report.alerts.length} alerts to review`}/></section>
  <section className="reports-grid"><article className="panel"><div className="panel-title"><div><h2>Driver scorecard</h2><p>Daily output for every assigned route.</p></div><BarChart3/></div><div className="table-wrap"><table><thead><tr><th>Driver</th><th>Progress</th><th>Boxes</th><th>Invoice value</th><th>Issues</th><th>Last delivery</th></tr></thead><tbody>{report.drivers.map(d=><tr key={d.driverName}><td><strong>{d.driverName}</strong></td><td>{d.completedStops}/{d.assignedStops}</td><td>{d.deliveredBoxes}/{d.boxes}</td><td>{money(d.invoiceValue)}</td><td><span className={d.issueStops?'badge warn':'badge'}>{d.issueStops}</span></td><td>{d.lastDelivery?new Date(d.lastDelivery).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'}</td></tr>)}</tbody></table></div></article>
  <article className="panel alerts-panel"><div className="panel-title"><div><h2>Action center</h2><p>Shortages, delivery issues and missing proof.</p></div><AlertTriangle/></div>{report.alerts.length===0?<div className="all-clear"><CheckCircle2/><strong>All clear</strong><span>No operational exceptions detected.</span></div>:<div className="alert-list">{report.alerts.map((a,i)=><div className={`report-alert ${a.severity}`} key={i}><AlertTriangle/><div><strong>{a.title}</strong><span>{a.detail}</span></div></div>)}</div>}</article></section>
  <section className="panel"><div className="panel-title"><div><h2>30-day delivery activity</h2><p>Daily stop volume and completion trend.</p></div></div><div className="history-chart">{history.map(x=><div className="history-day" key={x.date} title={`${x.date}: ${x.completed}/${x.stops} completed`}><div className="bars"><i style={{height:`${Math.max(3,x.stops/max*100)}%`}}/><b style={{height:`${Math.max(2,x.completed/max*100)}%`}}/></div><span>{new Date(`${x.date}T12:00:00`).toLocaleDateString([],{month:'short',day:'numeric'})}</span></div>)}</div><div className="chart-legend"><span><i/>Assigned</span><span><b/>Completed</span></div></section>
  <section className="panel"><h2>Stop-by-stop audit</h2><div className="table-wrap"><table><thead><tr><th>#</th><th>Customer</th><th>Driver</th><th>Boxes</th><th>Status</th><th>Proof</th><th>Notes</th></tr></thead><tbody>{report.stops.map(s=><tr key={s.id}><td>{s.sequence||'—'}</td><td><strong>{s.customer.name}</strong><br/><small>{s.customer.address}</small></td><td>{s.driver?.user?.name||'Unassigned'}</td><td>{s.deliveredBoxes??'—'} / {s.boxCount}</td><td><span className={`badge status-${s.status.toLowerCase()}`}>{s.status.replace('_',' ')}</span></td><td>{s.proofPhotoUrl?'Yes':'No'}</td><td>{s.notes||'—'}</td></tr>)}</tbody></table></div></section>
 </div>
}
function Kpi({icon,label,value,note}){return <article><div>{icon}</div><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
